// Generated by IoAddrGenerator — do not edit manually.
// Regenerate with: sbt "atari/runMain atari800.Atari800Ep4cgx150DualPllSv"
package atari;

import com.jopdesign.sys.Const;

/** Auto-allocated I/O addresses for all JOP devices. */
public class IoAddr {

	public static final int SIOBRIDGE = Const.IO_BASE + 0x30;
	public static final int SIOBRIDGE_STATUS_CTRL = SIOBRIDGE;
	public static final int SIOBRIDGE_RX_DATA = SIOBRIDGE + 1;
	public static final int SIOBRIDGE_TX_DATA = SIOBRIDGE + 2;
	public static final int SIOBRIDGE_TX_STATUS = SIOBRIDGE + 3;
	public static final int SIOBRIDGE_BAUD_DIV = SIOBRIDGE + 4;
	public static final int SIOBRIDGE_RX_STATUS = SIOBRIDGE + 5;

	public static final int VGATEXT = Const.IO_BASE + 0x40;
	public static final int VGATEXT_STATUS_CTRL = VGATEXT;
	public static final int VGATEXT_CURSOR = VGATEXT + 1;
	public static final int VGATEXT_WRITE_CHAR_ATTR = VGATEXT + 2;
	public static final int VGATEXT_DEFAULT_ATTR = VGATEXT + 3;
	public static final int VGATEXT_PALETTE = VGATEXT + 4;
	public static final int VGATEXT_COLS = VGATEXT + 5;
	public static final int VGATEXT_ROWS = VGATEXT + 6;
	public static final int VGATEXT_DIRECT_WRITE = VGATEXT + 7;
	public static final int VGATEXT_CLEAR = VGATEXT + 8;
	public static final int VGATEXT_SCROLL = VGATEXT + 9;
	public static final int VGATEXT_H_TEXT_START = VGATEXT + 10;
	public static final int VGATEXT_V_TEXT_START = VGATEXT + 11;

	public static final int ATARICTRL = Const.IO_BASE + 0x50;
	public static final int ATARICTRL_STATUS_CTRL = ATARICTRL;
	public static final int ATARICTRL_CART_SELECT = ATARICTRL + 1;
	public static final int ATARICTRL_CONFIG = ATARICTRL + 2;
	public static final int ATARICTRL_PADDLE_01 = ATARICTRL + 3;
	public static final int ATARICTRL_PADDLE_23 = ATARICTRL + 4;
	public static final int ATARICTRL_PADDLE_45 = ATARICTRL + 5;
	public static final int ATARICTRL_PADDLE_67 = ATARICTRL + 6;
	public static final int ATARICTRL_JOY_12 = ATARICTRL + 7;
	public static final int ATARICTRL_JOY_34 = ATARICTRL + 8;
	public static final int ATARICTRL_KB_THROTTLE = ATARICTRL + 9;
	public static final int ATARICTRL_CART_SLOT_ADDR = ATARICTRL + 10;
	public static final int ATARICTRL_CART_SLOT_DATA = ATARICTRL + 11;
	public static final int ATARICTRL_KEYBOARD = ATARICTRL + 12;

	public static final int SDSPI = Const.IO_BASE + 0x68;
	public static final int SDSPI_STATUS = SDSPI;
	public static final int SDSPI_DATA = SDSPI + 1;
	public static final int SDSPI_CLK_DIV = SDSPI + 2;

	public static final int UART = Const.IO_BASE + 0x6e;
	public static final int UART_STATUS = UART;
	public static final int UART_DATA = UART + 1;

	// Interrupt numbers
	public static final int INT_TIMER = 0;
	public static final int INT_UART = 1;
	public static final int INT_VGATEXT = 3;
	public static final int INT_SIOBRIDGE = 4;
	public static final int INT_SDSPI = 5;
}
